export const SYSTEM_MODE = "SYSTEM_MODE";
export const SHOW_HIDE_SIDEBAR = "SHOW_HIDE_SIDEBAR";
export const lOGINPAGECOUNTER = "lOGINPAGECOUNTER";
export const REDUCE_SIDEBAR = "REDUCE_SIDEBAR";
export const DASHBOARD_NAV_DROPDOWN = "DASHBOARD_NAV_DROPDOWN";
export const LOGIN = "LOGIN";
export const ALLOWED_ACCESS = "ALLOWED_ACCESS";
export const LOGOUT = "LOGOUT";
