import React from "react";
import Ads from "../postAdsStructure/ads";
import { ArticleDisplayDiv } from "./styles/articleDisplay.style";
import image1 from "../../assets/Images/Avatar.png";
import Image from "next/image";
import { MdOutlineBookmarkAdd } from "react-icons/md";
import { FiMoreHorizontal } from "react-icons/fi";
import {
  BsFillHandThumbsUpFill,
  BsFillHandThumbsDownFill,
} from "react-icons/bs";
import photoSix from "../../assets/Images/about-us.jpg";

import { FaCommentDots } from "react-icons/fa";

const ArticleDisplay = () => {
  return (
    <ArticleDisplayDiv>
      <div className={"articleWrapper"}>
        <div className={"articleWrapper__header"}>
          <div className={"articleWrapper__headerProfile"}>
            <div className={"articleWrapper__headerProfilePics"}>
              <Image
                src={image1}
                alt="state"
                className={"articleWrapper__headerProfilePicsItem"}
              />
            </div>
            <div className={"articleWrapper__headerProfileDetails"}>
              <p className={"articleWrapper__headerProfileDetailsHeader"}>
                Joshua Ejike
              </p>
              <p className={"articleWrapper__headerProfileDetailsParagraph"}>
                Aug 24
              </p>
            </div>
          </div>
          <div className={"articleWrapper__headerProfileSectionState"}>
            <div className={"articleWrapper__headerProfileSectionStateSave"}>
              <MdOutlineBookmarkAdd
                className={"articleWrapper__headerProfileSectionStateSaveItem"}
              />
            </div>
            <div className={"articleWrapper__headerProfileSectionStateFollow"}>
              <FiMoreHorizontal
                className={
                  "articleWrapper__headerProfileSectionStateFollowItem"
                }
              />
            </div>
          </div>
        </div>
        <div className={"articleWrapper__title"}>
          <div className={"articleWrapper__titleDetails"}>
            <p className={"articleWrapper__titleDetailsItem"}>
              this is a sttesd mi
            </p>
          </div>

          <div className={"articleWrapper__titleImageWrapper"}>
            <Image
              src={photoSix}
              alt={""}
              priority
              placeholder={"blur"}
              // blurDataURL
              objectFit={"cover"}
              layout={"responsive"}
              className={"articleWrapper__titleImageWrapperItem"}
            />
          </div>
        </div>
        <div className={"articleWrapper__articleDetails"}>
          <p className={"articleWrapper__articleDetailsItem"}>
            Privacy Policy 1. Introduction Welcome to Slem InfoTech. Slem
            InfoTech (“us”, “we”, or “our”) operates Slem InfoTech (hereinafter
            referred to as “Service”). Our Privacy Policy governs your visit to
            Slem InfoTech, and explains how we collect, safeguard and disclose
            information that results from your use of our Service. We use your
            data to provide and improve Service. By using Service, you agree to
            the collection and use of information in accordance with this
            policy. Unless otherwise defined in this Privacy Policy, the terms
            used in this Privacy Policy have the same meanings as in our Terms
            and Conditions. Our Terms and Conditions (“Terms”) govern all use of
            our Service and together with the Privacy Policy constitutes your
            agreement with us (“agreement”). 2. Definitions SERVICE means the
            Slem InfoTech website operated by Slem InfoTech. PERSONAL DATA means
            data about a living individual who can be identified from that data
            (or from those and other information either in our possession or
            likely to come into our possession). USAGE DATA is data collected
            automatically either generated by the use of Service or from Service
            infrastructure itself (for example, the duration of a page visit).
            COOKIES are small files stored on your device (computer or mobile
            device). DATA CONTROLLER means a natural or legal person who (either
            alone or jointly or in common with other persons) determines the
            purposes for which and the manner in which any personal data are, or
            are to be, processed. For the purpose of this Privacy Policy, we are
            a Data Controller of your data. DATA PROCESSORS (OR SERVICE
            PROVIDERS) means any natural or legal person who processes the data
            on behalf of the Data Controller. We may use the services of various
            Service Providers in order to process your data more effectively.
          </p>
        </div>
        <div className={"articleWrapper__SocialMedai"}>
          <div className={"articleWrapper__SocialMedaiDetails"}>
            <div className={"articleWrapper__SocialMedaiDetailsLike"}>
              <div className={"articleWrapper__SocialMedaiDetailsLikeIconBody"}>
                <BsFillHandThumbsUpFill
                  className={"articleWrapper__SocialMedaiDetailsLikeIcon"}
                />
              </div>
              <div className={"articleWrapper__SocialMedaiDetailsLikeContent"}>
                <p>like</p>
              </div>
            </div>
            <div className={"articleWrapper__SocialMedaiDetailsLike"}>
              <div className={"articleWrapper__SocialMedaiDetailsLikeIconBody"}>
                <BsFillHandThumbsDownFill
                  className={"articleWrapper__SocialMedaiDetailsLikeIcon"}
                />
              </div>
              <div className={"articleWrapper__SocialMedaiDetailsLikeContent"}>
                <p>dislike</p>
              </div>
            </div>
            <div className={"articleWrapper__SocialMedaiDetailsLike"}>
              <div className={"articleWrapper__SocialMedaiDetailsLikeIconBody"}>
                <FaCommentDots
                  className={"articleWrapper__SocialMedaiDetailsLikeIcon"}
                />
              </div>
              <div className={"articleWrapper__SocialMedaiDetailsLikeContent"}>
                <p>Comments</p>
              </div>
            </div>
          </div>
          <div className={"articleWrapper__SocialMedaiStatus"}>
            <div className={"articleWrapper__SocialMedaiStatusSaveIconBody"}>
              <MdOutlineBookmarkAdd
                className={"articleWrapper__SocialMedaiStatusSaveIcon"}
              />
            </div>
            <div className={"articleWrapper__SocialMedaiStatusFollowIconBody"}>
              <FiMoreHorizontal
                className={"articleWrapper__SocialMedaiStatusFollowIcon"}
              />
            </div>
          </div>
        </div>
        <div className="articleWrapper__comment">
          <div className="articleWrapper__commentSection">
            <div className="articleWrapper__commentSectionImageWrapper">
              <Image
                src={image1}
                alt="state"
                width={50}
                height={50}
                className="articleWrapper__commentSectionImage"
              />
            </div>
            <div className="articleWrapper__commentSectionStage">
              <div className="articleWrapper__commentSectionStageTitle">
                <p>joshua ejike</p>
              </div>
              <textarea className="articleWrapper__commentSectionStageTextarea" />
              <div className="articleWrapper__commentSectionStageButton">
                <button>Comment</button>
              </div>
            </div>
          </div>
          <div className="articleWrapper__commentTextSectionWrapper">
            {ArrayList?.map((item, key) => (
              <div key={key} className="articleWrapper__commentTextSection">
                <div className="articleWrapper__commentTextSectionWImageWrapper">
                  <Image
                    src={image1}
                    alt="state"
                    width={30}
                    height={30}
                    className="articleWrapper__commentTextSectionWImage"
                  />
                </div>
                <div className="articleWrapper__commentTextSectionText">
                  <div className="articleWrapper__commentTextSectionTextTitle">
                    <p>
                      Sam Doe{" "}
                      <span className="articleWrapper__commentTextSectionTextTitleSpan">
                        on Aug 17, 2021 5:34 am
                      </span>
                    </p>
                  </div>
                  <div className="articleWrapper__commentTextSectionTextBody">
                    <p>
                      That far ground rat pure from newt far panther crane
                      lorikeet overlay alas cobra across much gosh less
                      goldfinch ruthlessly alas examined and that more and the
                      ouch jeez.
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className={"articleWrapperAds"}>
        <Ads />
      </div>
    </ArticleDisplayDiv>
  );
};

const ArrayList = [
  {
    text: "That far ground rat pure from newt far panther crane lorikeet overlay alas cobra across much gosh less goldfinch ruthlessly alas examined and that more and the ouch jeez.",
  },
  {
    text: "That far ground rat pure from newt far panther crane lorikeet overlay alas cobra across much gosh less goldfinch ruthlessly alas examined and that more and the ouch jeez.",
  },
  {
    text: "That far ground rat pure from newt far panther crane lorikeet overlay alas cobra across much gosh less goldfinch ruthlessly alas examined and that more and the ouch jeez.",
  },
  {
    text: "That far ground rat pure from newt far panther crane lorikeet overlay alas cobra across much gosh less goldfinch ruthlessly alas examined and that more and the ouch jeez.",
  },
];

export default ArticleDisplay;
